### ISSUE TITLE
AttributeError after calling search_tweets(query_type="all")

### ISSUE THREAD

**Issue by 9tin9tin9** [sns-sdks/python-twitter#120]
I tried to retrieve all tweets from an account by calling search_tweets with the following function and got this error
code:
```python3
def load_tweets(refresh = False):
    if refresh:
        # api = Api(bearer_token=os.environ["bearer_token"])
        api = Api(client_id=os.environ["client_id"], client_secret=os.environ["client_secret"], oauth_flow=True)
        authorization_url, code_verifier, state = api.get_oauth2_authorize_url()
        print(authorization_url)
        response_url = input("Response: ")
        user_token = api.generate_oauth2_access_token(response=response_url, code_verifier=code_verifier)

        response = api.search_tweets(query="from:lokxii_ lang:en", query_type="all")
        tweets = [tweet.text for tweet in reversed(response.data)]
        # cache them
        with open("tweets.txt", "w") as f:
            for tweet in tweets:
                f.write(f"{tweet}\n")

    with open("tweets.txt") as f:
        return f.read().splitlines()
```
the function is called with `refresh=True`
Error message:
```
Traceback (most recent call last):
  File "/Users/austinsiu/program/lokxii_bot/main.py", line 44, in <module>
    main()
  File "/Users/austinsiu/program/lokxii_bot/main.py", line 40, in main
    tweets = load_tweets(refresh=True)
  File "/Users/austinsiu/program/lokxii_bot/main.py", line 20, in load_tweets
    response = api.search_tweets(query="from:lokxii_ lang:en", query_type="all")
  File "/usr/local/lib/python3.9/site-packages/pytwitter/api.py", line 935, in search_tweets
    return self._get(
  File "/usr/local/lib/python3.9/site-packages/pytwitter/api.py", line 420, in _get
    resp = self._request(url=url, params=params)
  File "/usr/local/lib/python3.9/site-packages/pytwitter/api.py", line 163, in _request
    resp = self.session.request(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 320, in prepare
    self.prepare_auth(auth, url)
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 556, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python3.9/site-packages/authlib/integrations/requests_client/oauth2_session.py", line 36, in __call__
    req.url, req.headers, req.body = self.prepare(
  File "/usr/local/lib/python3.9/site-packages/authlib/oauth2/auth.py", line 95, in prepare
    token_type = self.token.get('token_type', self.DEFAULT_TOKEN_TYPE)
AttributeError: 'str' object has no attribute 'get'
```
This only happens when I call search_tweets with `query_type="all"` but not with `"recent"`
May I know what did I do wrong and how to solve this?

**Comment by MerleLiuKun** [comment]
The query type for `all`,  Only for who have been approved for the `Academic Research product track`. Maybe your app not have this permissions.

**Comment by MerleLiuKun** [comment]
And This error maybe a mistake for token handler. I will solve it quickly. 

Before the fix version,  You can reinitial api with the generated token. Like this.

```python
from authlib.integrations.requests_client import OAuth2Auth

....
user_token = api.generate_oauth2_access_token(response=response_url, code_verifier=code_verifier)
api._auth = OAuth2Auth(
      token={"access_token": bearer_token, "token_type": "Bearer"}
)
.....
```
