### ISSUE TITLE
Media upload error

### ISSUE THREAD

**Issue by bazuker** [sns-sdks/python-twitter#157]
```Python
import base64
import os
from pytwitter import Api

api = Api(
    consumer_key=os.environ['TWITTER_API_KEY'],
    consumer_secret=os.environ['TWITTER_API_SECRET'],
    access_token=os.environ['TWITTER_1STOP_BJJ_ACCESS_TOKEN'],
    access_secret=os.environ['TWITTER_1STOP_BJJ_SECRET']
)
with open("final.mp4", "rb") as media:
    media_data = base64.b64encode(media.read()).decode("utf-8")
    resp_json = api.upload_media_simple(
        media_data=media_data,
        return_json=True,
    )
```

```
Traceback (most recent call last):
  File "/Users/bazuker/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bazuker/Library/Python/3.9/lib/python/site-packages/pytwitter/api.py", line 394, in _parse_response
    data = resp.json()
  File "/Users/bazuker/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bazuker/bazuker/src/crosspost-master/scripts/twitter_upload.py", line 15, in <module>
    resp_json = api.upload_media_simple(
  File "/Users/bazuker/Library/Python/3.9/lib/python/site-packages/pytwitter/api.py", line 608, in upload_media_simple
    data = self._parse_response(resp=resp)
  File "/Users/bazuker/Library/Python/3.9/lib/python/site-packages/pytwitter/api.py", line 396, in _parse_response
    raise PyTwitterError(f"Unknown error: {resp.content}")
pytwitter.error.PyTwitterError: Unknown error: b''
```

Unhandled error. Not sure what to do from here.

**Comment by bazuker** [comment]
Figured I need to use chunked upload. Closing.
